//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int productid { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public Nullable<int> Category_Categoryid { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
    }
}
